[tool.poetry]
name = "rag-chroma-private"
version = "0.1.0"
description = ""
authors = [
    "Lance Martin <lance@langchain.dev>",
]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8.1,<4.0"
langchain = ">=0.0.325"
tiktoken = ">=0.5.1"
chromadb = ">=0.4.14"
gpt4all = ">=1.0.8"
beautifulsoup4 = ">=4.12.2"

[tool.poetry.group.dev.dependencies]
langchain-cli = ">=0.0.15"

[tool.langserve]
export_module = "rag_chroma_private"
export_attr = "chain"

[build-system]
requires = [
    "poetry-core",
]
build-backend = "poetry.core.masonry.api"
